// A.AA ANALYTICS-REAL: typed adapter over the REAL @geezjulz TikTok summary.
//
// SOURCE: data/tiktok-summary.json (generated by import-real-data.mjs from
//   julz-vault tiktok_data_enhanced.csv — 42 real @geezjulz posts).
//
// HR-10 / HR-49 ACCESS HONESTY + NO MOCK DATA: the CSV/summary has likes,
//   comments and shares ONLY — there are NO view counts, NO watch-time, NO
//   click/conversion, NO earnings/bonus data, and shares are all 0. This
//   adapter exposes the metrics that genuinely exist and NEVER invents the
//   ones that don't. Components that previously rendered fabricated
//   views/earnings/bonus numbers are repointed to real engagement metrics or
//   honestly emptied. See `HONEST_GAPS` for the explicit omissions.
//
// Pairs with from-tiktok-csv.ts (the time-series + hook adapter used by the
// chart components). This file covers the summary aggregates + top-posts list.

import summary from '@/data/tiktok-summary.json';

export interface PillarSummary {
  pillar: string;
  posts: number;
  likes: number;
  comments: number;
  shares: number;
  /** likes + comments + shares */
  engagement: number;
  /** (likes + comments + shares) / posts, rounded */
  avgEngagement: number;
}

export interface TopPostSummary {
  postId: string;
  caption: string;
  likes: number;
  comments: number;
  shares: number;
  /** likes + comments + shares */
  engagement: number;
  pillar: string;
  url: string;
}

export interface TikTokSummaryTotals {
  totalPosts: number;
  likes: number;
  comments: number;
  shares: number;
  /** likes + comments + shares across all posts */
  engagement: number;
  /** avg engagement per post, as reported by the ETL */
  avgEngagementPerPost: number;
}

interface RawPillar {
  pillar: string;
  posts: number;
  likes: number;
  comments: number;
  shares: number;
}

interface RawTopPost {
  post_id: string;
  caption: string;
  likes: number;
  comments: number;
  shares: number;
  pillar: string;
  url: string;
}

/** Real account-level totals from the @geezjulz CSV. */
export function getTikTokSummaryTotals(): TikTokSummaryTotals {
  const likes = summary.likes ?? 0;
  const comments = summary.comments ?? 0;
  const shares = summary.shares ?? 0;
  return {
    totalPosts: summary.total_posts ?? 0,
    likes,
    comments,
    shares,
    engagement: likes + comments + shares,
    avgEngagementPerPost: summary.avg_engagement_per_post ?? 0,
  };
}

/** Per-pillar performance, sorted by engagement desc (top pillar first). */
export function getPillarSummary(): PillarSummary[] {
  const rows = (summary.by_pillar ?? []) as RawPillar[];
  return rows
    .map((r) => {
      const engagement = r.likes + r.comments + r.shares;
      return {
        pillar: r.pillar,
        posts: r.posts,
        likes: r.likes,
        comments: r.comments,
        shares: r.shares,
        engagement,
        avgEngagement: r.posts ? Math.round(engagement / r.posts) : 0,
      };
    })
    .sort((a, b) => b.engagement - a.engagement);
}

/** Real best-performing posts (already engagement-ranked in the source). */
export function getTopPosts(): TopPostSummary[] {
  const rows = (summary.top_posts ?? []) as RawTopPost[];
  return rows.map((p) => ({
    postId: p.post_id,
    caption: p.caption,
    likes: p.likes,
    comments: p.comments,
    shares: p.shares,
    engagement: p.likes + p.comments + p.shares,
    pillar: p.pillar,
    url: p.url,
  }));
}

/**
 * Real, source-derived headline KPIs for the top stat strip.
 * Only metrics that EXIST in the @geezjulz CSV — no views, no earnings.
 */
export function getTopStats(): Array<{
  id: string;
  label: string;
  value: string;
  sublabel?: string;
}> {
  const t = getTikTokSummaryTotals();
  return [
    {
      id: 'posts',
      label: 'TOTAL POSTS',
      value: t.totalPosts.toLocaleString(),
      sublabel: '@geezjulz · all time',
    },
    {
      id: 'likes',
      label: 'TOTAL LIKES',
      value: t.likes.toLocaleString(),
      sublabel: 'across all posts',
    },
    {
      id: 'comments',
      label: 'TOTAL COMMENTS',
      value: t.comments.toLocaleString(),
      sublabel: 'across all posts',
    },
    {
      id: 'avg-eng',
      label: 'AVG ENGAGEMENT',
      value: t.avgEngagementPerPost.toLocaleString(),
      sublabel: 'likes + comments per post',
    },
  ];
}

/**
 * HR-10 honesty manifest: metrics the @geezjulz CSV does NOT contain, so the
 * dashboard does not fabricate them. Surfaced in the UI where a fabricated
 * panel used to live (e.g. the empty-state note on bonus/links cards).
 */
export const HONEST_GAPS = {
  hasViews: false,
  hasWatchTime: false,
  hasShares: false, // present in schema but all values are 0
  hasClicksConversions: false,
  hasEarningsBonus: false,
  note: 'Source CSV (julz-vault tiktok_data_enhanced.csv) reports likes & comments only — no views, watch-time, link clicks, conversions or earnings.',
} as const;

/** Source-of-truth provenance string for footnotes. */
export const TIKTOK_SOURCE = {
  source: summary.source ?? 'julz-vault tiktok_data_enhanced.csv (REAL @geezjulz)',
  generatedBy: summary._generated ?? 'import-real-data.mjs',
} as const;
