// Phase A.14n Wave 2b — N3-PIPELINE-PQ: density fix for /pipeline/board.
//
// Source: N1-V2 visual baseline gap #8 (`06-a14n-visual-baseline.md` L80):
//   "/pipeline/board shows only 3 columns w/ ~1 card vs mockup's 8-column
//    dense kanban" — appears to be missing campaign data OR column-filter
//    is hiding 5 stages.
//
// Root cause: `MOCK_CAMPAIGNS` (canonical Campaign[] in
// `campaigns/index.ts`) only contains 6 campaigns, spread across 5 stages.
// The board renders all 19 stages but only 5 columns have cards. Mockups
// #14 + #23 show 3-4 cards per column across most stages.
//
// HR-2 PRESERVE INTENT: rather than mutate `MOCK_CAMPAIGNS` (consumed by
// 24 files including overview/analytics/payments/contacts/scoring tests),
// this file exports a SECONDARY set used ONLY by the board page. The 6
// canonical campaigns remain the source of truth for everything else —
// counts, links, scoring, payments all stay stable.
//
// Mockup citations:
//   - #14 (pipeline-kanban): 8-col dense kanban, 2-4 cards per visible col
//   - #23 (pipeline-kanban-creator-dense): wider density, ~3 cards per col
//                                          with avatar + brand + meta
//
// Cards intentionally lean on minimal fields (brand, stage, value, dates,
// priority, type) — enough for PipelineCardCampaign to render. No
// scoring/CRM/messaging fields because these synthetic rows never land in
// any non-board view.

import type { Campaign } from '@/lib/types/campaign';

/**
 * Synthetic campaigns added to the board kanban to match mockup density.
 *
 * Distribution targets approx 2-3 cards per stage across the 18 active
 * stages (skip ARCHIVED — mockup keeps that column quiet). Brand names
 * are pulled from BOARD_TOP_BRANDS + UPCOMING_DEADLINES + RECENT_ACTIVITY
 * already on the page so the rail's "Top brands" feels coherent.
 */
export const BOARD_EXTRA_CAMPAIGNS: Campaign[] = [
  // ── NEW LEAD (target: 3) ───────────────────────────────────────────────
  {
    campaign_id: 'extra-newlead-1',
    brand: 'Caraway',
    product: 'Ceramic non-stick pan',
    campaign_name: 'Caraway — Kitchen Refresh',
    platform_source: 'sideshift',
    contact_name: 'Talia',
    contact_channel: 'sideshift',
    current_stage: 'NEW LEAD',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'demo',
    product_category: 'home',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-06-12',
    base_pay: 1200,
    total_potential_value: 1500,
    payment_status: 'unknown',
    risk_level: 'low',
    next_action: 'Reply to SideShift brief by Friday',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-newlead-2',
    brand: 'Olipop',
    product: 'Probiotic soda · summer flavor',
    campaign_name: 'Olipop — Strawberry Vanilla Drop',
    platform_source: 'email',
    contact_name: 'Reece',
    contact_channel: 'email',
    current_stage: 'NEW LEAD',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'organic_post',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-06-15',
    base_pay: 850,
    total_potential_value: 1100,
    payment_status: 'unknown',
    risk_level: 'low',
    next_action: 'Pitch hook angles by Mon',
    blockers: [],
    missing_info: ['flavor sample timing'],
  },
  {
    campaign_id: 'extra-newlead-3',
    brand: 'Liquid Death',
    product: 'Mountain Water 4-pack',
    campaign_name: 'Liquid Death — Murder Your Thirst',
    platform_source: 'inbound',
    contact_name: 'Andy',
    contact_channel: 'email',
    current_stage: 'NEW LEAD',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'me',
    campaign_type: 'paid_ad',
    product_category: 'other',
    deliverable_count: 2,
    required_format: 'vertical_video',
    due_date: '2026-06-18',
    base_pay: 1800,
    total_potential_value: 2400,
    payment_status: 'unknown',
    risk_level: 'low',
    next_action: 'Send rate card',
    blockers: [],
    missing_info: [],
  },

  // ── APPLIED (target: 2) ────────────────────────────────────────────────
  {
    campaign_id: 'extra-applied-1',
    brand: 'Rare Beauty',
    product: 'Soft Pinch Liquid Blush',
    campaign_name: 'Rare Beauty — Tone Match Tutorial',
    platform_source: 'sideshift',
    contact_name: 'Selena’s team',
    contact_channel: 'sideshift',
    current_stage: 'APPLIED',
    status: 'waiting',
    priority: 'high',
    waiting_on_who: 'brand',
    campaign_type: 'review',
    product_category: 'beauty',
    deliverable_count: 1,
    required_format: 'vertical_video',
    follow_up_date: '2026-05-28',
    base_pay: 950,
    total_potential_value: 1300,
    payment_status: 'unknown',
    risk_level: 'low',
    next_action: 'Await application review',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-applied-2',
    brand: 'Drunk Elephant',
    product: 'Protini Polypeptide Cream',
    campaign_name: 'Drunk Elephant — Morning Routine',
    platform_source: 'sideshift',
    contact_name: 'Marcus',
    contact_channel: 'sideshift',
    current_stage: 'APPLIED',
    status: 'waiting',
    priority: 'medium',
    waiting_on_who: 'brand',
    campaign_type: 'organic_post',
    product_category: 'beauty',
    deliverable_count: 1,
    required_format: 'vertical_video',
    follow_up_date: '2026-05-30',
    base_pay: 700,
    total_potential_value: 950,
    payment_status: 'unknown',
    risk_level: 'low',
    next_action: 'Await SideShift accept',
    blockers: [],
    missing_info: [],
  },

  // ── BRAND REPLIED (target: 2 additional, megprime is already there) ───
  {
    campaign_id: 'extra-replied-1',
    brand: 'Whoop',
    product: 'Whoop 4.0 strap',
    campaign_name: 'Whoop — Recovery Score Series',
    platform_source: 'email',
    contact_name: 'Priya',
    contact_channel: 'email',
    current_stage: 'BRAND REPLIED',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'me',
    campaign_type: 'demo',
    product_category: 'other',
    deliverable_count: 3,
    required_format: 'vertical_video',
    due_date: '2026-06-22',
    base_pay: 2400,
    total_potential_value: 3200,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Send sample script by Wed',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-replied-2',
    brand: 'Our Place',
    product: 'Always Pan 2.0',
    campaign_name: 'Our Place — Apartment Cook',
    platform_source: 'email',
    contact_name: 'Layla',
    contact_channel: 'email',
    current_stage: 'BRAND REPLIED',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'review',
    product_category: 'home',
    deliverable_count: 2,
    required_format: 'vertical_video',
    due_date: '2026-06-25',
    base_pay: 1100,
    total_potential_value: 1500,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Confirm color preference',
    blockers: [],
    missing_info: [],
  },

  // ── RESPONDED (target: 3) ──────────────────────────────────────────────
  {
    campaign_id: 'extra-responded-1',
    brand: 'Glossier',
    product: 'Cloud Paint duo',
    campaign_name: 'Glossier — Blush Layering',
    platform_source: 'email',
    contact_name: 'Nia',
    contact_channel: 'email',
    current_stage: 'RESPONDED',
    status: 'waiting',
    priority: 'high',
    waiting_on_who: 'brand',
    campaign_type: 'review',
    product_category: 'beauty',
    deliverable_count: 2,
    required_format: 'vertical_video',
    follow_up_date: '2026-05-28',
    base_pay: 1400,
    total_potential_value: 1900,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Await brief confirmation',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-responded-2',
    brand: 'Ouai',
    product: 'Hair Oil + Detangler',
    campaign_name: 'Ouai — Wash Day Routine',
    platform_source: 'sideshift',
    contact_name: 'Brooke',
    contact_channel: 'sideshift',
    current_stage: 'RESPONDED',
    status: 'waiting',
    priority: 'medium',
    waiting_on_who: 'brand',
    campaign_type: 'organic_post',
    product_category: 'beauty',
    deliverable_count: 1,
    required_format: 'vertical_video',
    follow_up_date: '2026-05-30',
    base_pay: 800,
    total_potential_value: 1100,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Await timing',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-responded-3',
    brand: 'Notion',
    product: 'Notion Calendar launch',
    campaign_name: 'Notion — Calendar Beta Push',
    platform_source: 'email',
    contact_name: 'Devon',
    contact_channel: 'email',
    current_stage: 'RESPONDED',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'brand',
    campaign_type: 'demo',
    product_category: 'software',
    deliverable_count: 1,
    required_format: 'vertical_video',
    follow_up_date: '2026-05-26',
    base_pay: 1600,
    total_potential_value: 2200,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Hold for SOW',
    blockers: [],
    missing_info: ['feature freeze date'],
  },

  // ── WAITING ON BRAND (target: 3) ───────────────────────────────────────
  {
    campaign_id: 'extra-waiting-1',
    brand: 'Magic Mind',
    product: 'Productivity shot',
    campaign_name: 'Magic Mind — Morning Stack',
    platform_source: 'email',
    contact_name: 'Hannah',
    contact_channel: 'email',
    current_stage: 'WAITING ON BRAND',
    status: 'waiting',
    priority: 'medium',
    waiting_on_who: 'brand',
    campaign_type: 'review',
    product_category: 'other',
    deliverable_count: 2,
    required_format: 'vertical_video',
    follow_up_date: '2026-05-27',
    base_pay: 1000,
    total_potential_value: 1400,
    payment_status: 'pending',
    risk_level: 'medium',
    next_action: 'Bump for sample tracking #',
    blockers: ['Sample not shipped'],
    missing_info: ['sample tracking'],
  },
  {
    campaign_id: 'extra-waiting-2',
    brand: 'AG1',
    product: 'Green powder',
    campaign_name: 'AG1 — Daily Greens Test',
    platform_source: 'direct',
    contact_name: 'Tomás',
    contact_channel: 'email',
    current_stage: 'WAITING ON BRAND',
    status: 'waiting',
    priority: 'low',
    waiting_on_who: 'brand',
    campaign_type: 'review',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    follow_up_date: '2026-05-29',
    base_pay: 600,
    total_potential_value: 900,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Wait on brief draft',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-waiting-3',
    brand: 'Aritzia',
    product: 'Super Puff jacket',
    campaign_name: 'Aritzia — Fall Layer Look',
    platform_source: 'email',
    contact_name: 'Maeve',
    contact_channel: 'email',
    current_stage: 'WAITING ON BRAND',
    status: 'waiting',
    priority: 'high',
    waiting_on_who: 'brand',
    campaign_type: 'organic_post',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    follow_up_date: '2026-05-26',
    base_pay: 1300,
    total_potential_value: 1700,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Bump Maeve Mon',
    blockers: [],
    missing_info: ['shoot location'],
  },

  // ── CALL SCHEDULED (target: 2 additional, goodie-ai already there) ────
  {
    campaign_id: 'extra-call-1',
    brand: 'Linear',
    product: 'Linear for designers',
    campaign_name: 'Linear — Designer Workflow',
    platform_source: 'email',
    contact_name: 'Karri',
    contact_channel: 'call',
    current_stage: 'CALL SCHEDULED',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'brand',
    campaign_type: 'demo',
    product_category: 'software',
    deliverable_count: 1,
    required_format: 'vertical_video',
    call_date: '2026-05-27',
    base_pay: 1500,
    total_potential_value: 2000,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Prep 3 product questions',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-call-2',
    brand: 'Figma',
    product: 'Figma Sites',
    campaign_name: 'Figma — Sites Beta Walkthrough',
    platform_source: 'email',
    contact_name: 'Sara',
    contact_channel: 'call',
    current_stage: 'CALL SCHEDULED',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'brand',
    campaign_type: 'demo',
    product_category: 'software',
    deliverable_count: 1,
    required_format: 'vertical_video',
    call_date: '2026-05-29',
    base_pay: 1800,
    total_potential_value: 2500,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Confirm Loom recording OK',
    blockers: [],
    missing_info: [],
  },

  // ── SOW REVIEWED (target: 2) ───────────────────────────────────────────
  {
    campaign_id: 'extra-sowrev-1',
    brand: 'Athletic Greens',
    product: 'Travel pack 30ct',
    campaign_name: 'AG — Travel Routine',
    platform_source: 'email',
    contact_name: 'Petra',
    contact_channel: 'email',
    current_stage: 'SOW REVIEWED',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'organic_post',
    product_category: 'other',
    deliverable_count: 2,
    required_format: 'vertical_video',
    due_date: '2026-06-05',
    base_pay: 1100,
    total_potential_value: 1500,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Counter redline ¶3 (usage rights)',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-sowrev-2',
    brand: 'Hims',
    product: 'Skincare line',
    campaign_name: 'Hims — Daily Routine',
    platform_source: 'sideshift',
    contact_name: 'Jordan',
    contact_channel: 'sideshift',
    current_stage: 'SOW REVIEWED',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'me',
    campaign_type: 'review',
    product_category: 'beauty',
    deliverable_count: 3,
    required_format: 'vertical_video',
    due_date: '2026-06-10',
    base_pay: 2200,
    total_potential_value: 2800,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Sign SOW today',
    blockers: [],
    missing_info: [],
  },

  // ── STRATEGY READY (target: 2) ─────────────────────────────────────────
  {
    campaign_id: 'extra-strat-1',
    brand: 'Caraway',
    product: 'Bakeware launch',
    campaign_name: 'Caraway — Bake Set Debut',
    platform_source: 'direct',
    contact_name: 'Talia',
    contact_channel: 'email',
    current_stage: 'STRATEGY READY',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'demo',
    product_category: 'home',
    deliverable_count: 2,
    required_format: 'vertical_video',
    due_date: '2026-06-08',
    base_pay: 1700,
    total_potential_value: 2200,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Lock 3-hook strategy doc',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-strat-2',
    brand: 'Loom',
    product: 'Loom AI',
    campaign_name: 'Loom — AI Recap Showcase',
    platform_source: 'email',
    contact_name: 'Hen',
    contact_channel: 'email',
    current_stage: 'STRATEGY READY',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'me',
    campaign_type: 'demo',
    product_category: 'software',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-06-03',
    base_pay: 1900,
    total_potential_value: 2400,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Strategy doc → script',
    blockers: [],
    missing_info: [],
  },

  // ── SCRIPT READY (target: 2 additional, parakeetai is there) ──────────
  {
    campaign_id: 'extra-script-1',
    brand: 'Vuori',
    product: 'Performance jogger',
    campaign_name: 'Vuori — Travel Joggers',
    platform_source: 'email',
    contact_name: 'Tess',
    contact_channel: 'email',
    current_stage: 'SCRIPT READY',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'organic_post',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-06-01',
    base_pay: 1100,
    total_potential_value: 1400,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Schedule filming Sat',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-script-2',
    brand: 'Athletic Greens',
    product: 'AG1 single-serve',
    campaign_name: 'AG1 — Morning Pour',
    platform_source: 'direct',
    contact_name: 'Petra',
    contact_channel: 'email',
    current_stage: 'SCRIPT READY',
    status: 'active',
    priority: 'low',
    waiting_on_who: 'me',
    campaign_type: 'review',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-06-04',
    base_pay: 900,
    total_potential_value: 1200,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Shoot kitchen prep B-roll',
    blockers: [],
    missing_info: [],
  },

  // ── FILMING (target: 2 additional, elf is there) ───────────────────────
  {
    campaign_id: 'extra-film-1',
    brand: 'Glossier',
    product: 'Cloud Paint',
    campaign_name: 'Glossier — Cloud Layering',
    platform_source: 'email',
    contact_name: 'Nia',
    contact_channel: 'email',
    current_stage: 'FILMING',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'me',
    campaign_type: 'review',
    product_category: 'beauty',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-25',
    base_pay: 1400,
    total_potential_value: 1800,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Reshoot hook take 4',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-film-2',
    brand: 'Ouai',
    product: 'Hair oil',
    campaign_name: 'Ouai — Wash Day',
    platform_source: 'sideshift',
    contact_name: 'Brooke',
    contact_channel: 'sideshift',
    current_stage: 'FILMING',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'me',
    campaign_type: 'organic_post',
    product_category: 'beauty',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-26',
    base_pay: 1000,
    total_potential_value: 1300,
    payment_status: 'pending',
    risk_level: 'medium',
    next_action: 'Film 3-pack today',
    blockers: [],
    missing_info: ['shot of texture'],
  },

  // ── EDITING (target: 3) ────────────────────────────────────────────────
  {
    campaign_id: 'extra-edit-1',
    brand: 'Rare Beauty',
    product: 'Liquid blush',
    campaign_name: 'Rare Beauty — Hook Variants',
    platform_source: 'email',
    contact_name: 'Selena’s team',
    contact_channel: 'email',
    current_stage: 'EDITING',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'me',
    campaign_type: 'review',
    product_category: 'beauty',
    deliverable_count: 3,
    required_format: 'vertical_video',
    due_date: '2026-05-27',
    base_pay: 1600,
    total_potential_value: 2200,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Cut hook v2 — pacing tight',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-edit-2',
    brand: 'Olipop',
    product: 'Strawberry Vanilla',
    campaign_name: 'Olipop — Flavor Test',
    platform_source: 'email',
    contact_name: 'Reece',
    contact_channel: 'email',
    current_stage: 'EDITING',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'review',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-28',
    base_pay: 900,
    total_potential_value: 1200,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Sound mix + captions',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-edit-3',
    brand: 'Whoop',
    product: 'Recovery score',
    campaign_name: 'Whoop — Recovery Cut',
    platform_source: 'email',
    contact_name: 'Priya',
    contact_channel: 'email',
    current_stage: 'EDITING',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'demo',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-30',
    base_pay: 1100,
    total_potential_value: 1500,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Trim outro 3s',
    blockers: [],
    missing_info: [],
  },

  // ── QA (target: 2) ─────────────────────────────────────────────────────
  {
    campaign_id: 'extra-qa-1',
    brand: 'Olipop',
    product: 'Final delivery',
    campaign_name: 'Olipop — Final QA',
    platform_source: 'email',
    contact_name: 'Reece',
    contact_channel: 'email',
    current_stage: 'QA',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'me',
    campaign_type: 'review',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-22',
    base_pay: 900,
    total_potential_value: 1200,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Caption pass + sound check',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-qa-2',
    brand: 'Notion',
    product: 'Calendar reveal',
    campaign_name: 'Notion — Calendar Final',
    platform_source: 'email',
    contact_name: 'Devon',
    contact_channel: 'email',
    current_stage: 'QA',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'demo',
    product_category: 'software',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-24',
    base_pay: 1600,
    total_potential_value: 2200,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Brand-name pronunciation check',
    blockers: [],
    missing_info: [],
  },

  // ── SUBMITTED (target: 2) ──────────────────────────────────────────────
  {
    campaign_id: 'extra-sub-1',
    brand: 'Glossier',
    product: 'IG cut v3',
    campaign_name: 'Glossier — IG Cut v3',
    platform_source: 'email',
    contact_name: 'Nia',
    contact_channel: 'email',
    current_stage: 'SUBMITTED',
    status: 'submitted',
    priority: 'high',
    waiting_on_who: 'brand',
    campaign_type: 'review',
    product_category: 'beauty',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-20',
    base_pay: 1400,
    total_potential_value: 1900,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Await brand approval',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-sub-2',
    brand: 'Magic Mind',
    product: 'Morning shot review',
    campaign_name: 'Magic Mind — Shot Take',
    platform_source: 'email',
    contact_name: 'Hannah',
    contact_channel: 'email',
    current_stage: 'SUBMITTED',
    status: 'submitted',
    priority: 'medium',
    waiting_on_who: 'brand',
    campaign_type: 'review',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-19',
    base_pay: 950,
    total_potential_value: 1300,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Await Tue approval',
    blockers: [],
    missing_info: [],
  },

  // ── ACCEPTED (target: 2) ───────────────────────────────────────────────
  {
    campaign_id: 'extra-acc-1',
    brand: 'Vuori',
    product: 'Performance jogger',
    campaign_name: 'Vuori — Travel Jogger Final',
    platform_source: 'email',
    contact_name: 'Tess',
    contact_channel: 'email',
    current_stage: 'ACCEPTED',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'me',
    campaign_type: 'organic_post',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-18',
    base_pay: 1100,
    total_potential_value: 1400,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Schedule TikTok post',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-acc-2',
    brand: 'Loom',
    product: 'AI recap',
    campaign_name: 'Loom — AI Final',
    platform_source: 'email',
    contact_name: 'Hen',
    contact_channel: 'email',
    current_stage: 'ACCEPTED',
    status: 'active',
    priority: 'high',
    waiting_on_who: 'me',
    campaign_type: 'demo',
    product_category: 'software',
    deliverable_count: 1,
    required_format: 'vertical_video',
    due_date: '2026-05-17',
    base_pay: 1900,
    total_potential_value: 2400,
    payment_status: 'pending',
    risk_level: 'low',
    next_action: 'Schedule launch post',
    blockers: [],
    missing_info: [],
  },

  // ── POSTED (target: 3) ─────────────────────────────────────────────────
  {
    campaign_id: 'extra-post-1',
    brand: 'Our Place',
    product: 'Always Pan',
    campaign_name: 'Our Place — Pan TikTok',
    platform_source: 'direct',
    contact_name: 'Layla',
    contact_channel: 'email',
    current_stage: 'POSTED',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'payment',
    campaign_type: 'review',
    product_category: 'home',
    deliverable_count: 1,
    required_format: 'vertical_video',
    base_pay: 1100,
    total_potential_value: 1500,
    payment_status: 'invoiced',
    risk_level: 'low',
    next_action: 'Send invoice Net-30',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-post-2',
    brand: 'Whoop',
    product: 'Recovery cut',
    campaign_name: 'Whoop — Recovery Posted',
    platform_source: 'email',
    contact_name: 'Priya',
    contact_channel: 'email',
    current_stage: 'POSTED',
    status: 'active',
    priority: 'low',
    waiting_on_who: 'payment',
    campaign_type: 'demo',
    product_category: 'other',
    deliverable_count: 1,
    required_format: 'vertical_video',
    base_pay: 1100,
    total_potential_value: 1500,
    payment_status: 'invoiced',
    risk_level: 'low',
    next_action: 'Track view bonus',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-post-3',
    brand: 'Liquid Death',
    product: 'Mountain Water',
    campaign_name: 'Liquid Death — Posted Run',
    platform_source: 'inbound',
    contact_name: 'Andy',
    contact_channel: 'email',
    current_stage: 'POSTED',
    status: 'active',
    priority: 'medium',
    waiting_on_who: 'payment',
    campaign_type: 'paid_ad',
    product_category: 'other',
    deliverable_count: 2,
    required_format: 'vertical_video',
    base_pay: 1800,
    total_potential_value: 2400,
    payment_status: 'invoiced',
    risk_level: 'low',
    next_action: 'Net-30 send',
    blockers: [],
    missing_info: [],
  },

  // ── INVOICED (target: 2) ───────────────────────────────────────────────
  {
    campaign_id: 'extra-inv-1',
    brand: 'Caraway',
    product: 'Bake Set',
    campaign_name: 'Caraway — Bake Invoice',
    platform_source: 'direct',
    contact_name: 'Talia',
    contact_channel: 'email',
    current_stage: 'INVOICED',
    status: 'active',
    priority: 'low',
    waiting_on_who: 'payment',
    campaign_type: 'demo',
    product_category: 'home',
    deliverable_count: 2,
    required_format: 'vertical_video',
    base_pay: 1700,
    total_potential_value: 2200,
    payment_status: 'invoiced',
    risk_level: 'low',
    next_action: 'Net-30 reminder',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-inv-2',
    brand: 'Hims',
    product: 'Skincare set',
    campaign_name: 'Hims — Daily Set Invoice',
    platform_source: 'sideshift',
    contact_name: 'Jordan',
    contact_channel: 'sideshift',
    current_stage: 'INVOICED',
    status: 'active',
    priority: 'low',
    waiting_on_who: 'payment',
    campaign_type: 'review',
    product_category: 'beauty',
    deliverable_count: 3,
    required_format: 'vertical_video',
    base_pay: 2200,
    total_potential_value: 2800,
    payment_status: 'invoiced',
    risk_level: 'low',
    next_action: 'Net-30 reminder Fri',
    blockers: [],
    missing_info: [],
  },

  // ── PAID (target: 2) ───────────────────────────────────────────────────
  {
    campaign_id: 'extra-paid-1',
    brand: 'Whoop',
    product: 'Recovery campaign',
    campaign_name: 'Whoop — Recovery PAID',
    platform_source: 'email',
    contact_name: 'Priya',
    contact_channel: 'email',
    current_stage: 'PAID',
    status: 'paid',
    priority: 'low',
    waiting_on_who: 'none',
    campaign_type: 'demo',
    product_category: 'other',
    deliverable_count: 3,
    required_format: 'vertical_video',
    base_pay: 2400,
    total_potential_value: 3200,
    payment_status: 'paid',
    risk_level: 'low',
    next_action: 'Pitch retainer',
    blockers: [],
    missing_info: [],
  },
  {
    campaign_id: 'extra-paid-2',
    brand: 'Loom',
    product: 'AI launch',
    campaign_name: 'Loom — AI Launch PAID',
    platform_source: 'email',
    contact_name: 'Hen',
    contact_channel: 'email',
    current_stage: 'PAID',
    status: 'paid',
    priority: 'low',
    waiting_on_who: 'none',
    campaign_type: 'demo',
    product_category: 'software',
    deliverable_count: 1,
    required_format: 'vertical_video',
    base_pay: 1900,
    total_potential_value: 2400,
    payment_status: 'paid',
    risk_level: 'low',
    next_action: 'Send case-study draft',
    blockers: [],
    missing_info: [],
  },
];
